import { useLayoutEffect, useReducer, useRef, type ReactNode } from 'react'
import { AnimatePresence, motion, useReducedMotion } from 'motion/react'
import { Link } from 'react-router'
import { getSeedRecord, seedRecords, type SeedId, type SeedRecord } from './unsaidGardenContent.ts'
import { initialUnsaidGardenState, unsaidGardenReducer } from './unsaidGardenReducer.ts'
import { FlowerVisual, GreenhouseVisual } from './UnsaidGardenVisuals.tsx'
import styles from './UnsaidGardenPage.module.css'

const announcements = {
  arrival: 'Rumah kaca kecil Andre untuk Gusti sedang menunggu dibuka.', choosing: 'Pilih satu benih tersegel.', planting: 'Benih siap ditanam.', tending: 'Benih membutuhkan air dan cahaya.', bloom: 'Satu kata telah mekar.', herbarium: 'Tiga bunga sudah dipreservasi dalam herbarium.',
} as const

export function UnsaidGardenPage() {
  const [state, dispatch] = useReducer(unsaidGardenReducer, initialUnsaidGardenState)
  const shouldReduceMotion = useReducedMotion()
  const seed = state.selectedSeedId ? getSeedRecord(state.selectedSeedId) : null
  const preserved = state.preservedSeedIds.map(getSeedRecord)
  const scene = shouldReduceMotion ? { initial: false as const } : { initial: { opacity: 0, y: 12 } }

  return <section className={styles.garden} data-phase={state.phase}>
    <div className={styles.gardenHeader}><Link to="/">← Kembali ke koleksi</Link><p>The Unsaid Garden</p></div>
    <p className="visually-hidden" aria-live="polite" aria-atomic="true">{announcements[state.phase]}</p>
    <AnimatePresence mode="wait" initial={false}>
      {state.phase === 'arrival' && <SceneMotion key="arrival" reduce={shouldReduceMotion} {...scene}><Arrival onOpen={() => dispatch({ type: 'OPEN_GREENHOUSE' })} /></SceneMotion>}
      {state.phase === 'choosing' && <SceneMotion key="choosing" reduce={shouldReduceMotion} {...scene}><SeedTray preserved={state.preservedSeedIds} onChoose={(seedId) => dispatch({ type: 'SELECT_SEED', seedId })} /></SceneMotion>}
      {state.phase === 'planting' && seed && <SceneMotion key={`plant-${seed.id}`} reduce={shouldReduceMotion} {...scene}><Planting seed={seed} onPlant={() => dispatch({ type: 'PLANT_SEED' })} /></SceneMotion>}
      {state.phase === 'tending' && seed && <SceneMotion key={`tend-${seed.id}`} reduce={shouldReduceMotion} {...scene}><Tending seed={seed} state={state} onWater={() => dispatch({ type: 'WATER_SEED' })} onLight={() => dispatch({ type: 'ILLUMINATE_SEED' })} onBloom={() => dispatch({ type: 'BLOOM_SEED' })} /></SceneMotion>}
      {state.phase === 'bloom' && seed && <SceneMotion key={`bloom-${seed.id}`} reduce={shouldReduceMotion} {...scene}><Bloom seed={seed} preserved={preserved} isPreserved={state.preservedSeedIds.includes(seed.id)} onPreserve={() => dispatch({ type: 'PRESERVE_SEED' })} onHerbarium={() => dispatch({ type: 'OPEN_HERBARIUM' })} /></SceneMotion>}
      {state.phase === 'herbarium' && <SceneMotion key="herbarium" reduce={shouldReduceMotion} {...scene}><Herbarium preserved={preserved} onReplay={() => dispatch({ type: 'RESET' })} /></SceneMotion>}
    </AnimatePresence>
  </section>
}

function SceneMotion({ children, reduce }: { children: ReactNode; reduce: boolean | null }) { return <motion.div initial={reduce ? false : { opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={reduce ? undefined : { opacity: 0, y: -8 }} transition={{ duration: 0.26, ease: 'easeOut' }}>{children}</motion.div> }
function SceneTitle({ children, focus = true }: { children: ReactNode; focus?: boolean }) { const ref = useRef<HTMLHeadingElement>(null); useLayoutEffect(() => { if (focus) ref.current?.focus({ preventScroll: true }) }, [focus]); return <h1 className={styles.sceneTitle} ref={ref} tabIndex={-1}>{children}</h1> }

function Arrival({ onOpen }: { onOpen: () => void }) { return <div className={styles.arrivalScene}><div><p className={styles.kicker}>A TINY GREENHOUSE / FOR GUSTI</p><SceneTitle focus={false}>Ada beberapa kata yang belum siap diucapkan—jadi aku menanamnya.</SceneTitle><p className={styles.body}>Mungkin dengan sedikit waktu, air, dan cahaya, semuanya akan lebih berani untuk muncul.</p><aside className={styles.seedEnvelope}><span>FROM ANDRE</span><strong>FOR GUSTI</strong><em>HANDLE WITH PATIENCE</em></aside><button className={styles.primaryAction} type="button" onClick={onOpen}>Buka rumah kaca <span aria-hidden="true">→</span></button></div><GreenhouseVisual /></div> }

function SeedTray({ preserved, onChoose }: { preserved: readonly SeedId[]; onChoose: (seedId: SeedId) => void }) { return <div className={styles.trayScene}><div><p className={styles.kicker}>SEALED SEED TRAY</p><SceneTitle>Pilih satu benih yang belum kamu kenal.</SceneTitle><p className={styles.body}>Kamu belum tahu apa yang disimpannya. Pilih yang terasa sedang memanggilmu.</p></div><div className={styles.seedTray} aria-label="Pilihan benih tersegel">{seedRecords.map((seed) => { const used = preserved.includes(seed.id); return <button className={styles.seedPacket} data-accent={seed.accent} data-bloomed={used} disabled={used} key={seed.id} type="button" aria-label={used ? `${seed.label} sudah mekar` : `Pilih benih ${seed.label}`} onClick={() => onChoose(seed.id)}><FlowerVisual visualKey={seed.visualKey} bloomed={used} /><strong>{seed.label}</strong><span>{used ? 'BLOOMED' : 'SEALED'}</span></button> })}</div></div> }

function Planting({ seed, onPlant }: { seed: SeedRecord; onPlant: () => void }) { const targetRef = useRef<HTMLDivElement>(null); const onDragEnd = (_: unknown, info: { point: { x: number; y: number } }) => { const bounds = targetRef.current?.getBoundingClientRect(); if (bounds && info.point.x >= bounds.left - 24 && info.point.x <= bounds.right + 24 && info.point.y >= bounds.top - 24 && info.point.y <= bounds.bottom + 24) onPlant() }; return <div className={styles.plantingScene}><div><p className={styles.kicker}>PLANTING TABLE / {seed.label}</p><SceneTitle>Benih ini membutuhkan tempat kecil untuk tinggal.</SceneTitle><p className={styles.body}>Geser packet ke tanah, atau gunakan tombol tanam yang tersedia.</p><button className={styles.primaryAction} type="button" onClick={onPlant}>Tanam benih ini</button></div><div className={styles.plantingBench}><motion.button className={styles.dragPacket} type="button" drag dragConstraints={false} dragElastic={0.12} onDragEnd={onDragEnd} aria-label={`Geser benih ${seed.label} ke tanah`}><FlowerVisual visualKey={seed.visualKey} bloomed={false} /><span>{seed.label}</span></motion.button><div className={styles.soilTarget} data-testid="garden-soil-target" ref={targetRef}><span>TARUH BENIH DI SINI</span></div></div></div> }

function Tending({ seed, state, onWater, onLight, onBloom }: { seed: SeedRecord; state: Extract<ReturnType<typeof unsaidGardenReducer>, { phase: 'tending' }>; onWater: () => void; onLight: () => void; onBloom: () => void }) { const ready = state.care.watered && state.care.illuminated; return <div className={styles.tendingScene}><div><p className={styles.kicker}>GENTLE TENDING / {seed.label}</p><SceneTitle>Beberapa kata hanya membutuhkan sedikit perawatan.</SceneTitle><p className={styles.body}>Berikan air dan cahaya dalam urutan yang terasa tepat.</p><div className={styles.careTag}><span data-done={state.care.watered}>WATERED</span><span data-done={state.care.illuminated}>WARMED</span></div><div className={styles.careActions}><button type="button" aria-pressed={state.care.watered} onClick={onWater}>Siram benih</button><button type="button" aria-pressed={state.care.illuminated} onClick={onLight}>Beri cahaya</button></div><button className={styles.primaryAction} type="button" disabled={!ready} onClick={onBloom}>Biarkan ia mekar</button></div><GreenhouseVisual seed={seed} planted watered={state.care.watered} illuminated={state.care.illuminated} /></div> }

function Bloom({ seed, preserved, isPreserved, onPreserve, onHerbarium }: { seed: SeedRecord; preserved: readonly SeedRecord[]; isPreserved: boolean; onPreserve: () => void; onHerbarium: () => void }) { const ready = preserved.length >= 3; return <div className={styles.bloomScene}><div className={styles.bloomHouse}><GreenhouseVisual seed={seed} planted watered illuminated bloomed preserved={preserved.filter((item) => item.id !== seed.id)} /><span className={styles.messageLabel}>“{seed.message}”</span></div><article className={styles.bloomNote}><p className={styles.kicker}>A SMALL THING FINALLY SAID</p><SceneTitle>Sepertinya benih ini sudah siap.</SceneTitle><p className={styles.message}>“{seed.message}”</p><p className={styles.signature}>— Andre</p>{ready ? <button className={styles.primaryAction} type="button" onClick={onHerbarium}>Buka herbarium</button> : <button className={styles.primaryAction} type="button" disabled={isPreserved} onClick={onPreserve}>{isPreserved ? 'Tersimpan dengan care' : 'Simpan dan pilih benih lain'}</button>}</article></div> }

function Herbarium({ preserved, onReplay }: { preserved: readonly SeedRecord[]; onReplay: () => void }) { return <div className={styles.herbariumScene}><article className={styles.folio}><p className={styles.kicker}>PRESSED WITH CARE / ANDRE TO GUSTI</p><SceneTitle>Tidak semua yang terlambat dikatakan berarti kurang sungguh-sungguh.</SceneTitle><div className={styles.specimens}>{preserved.map((seed, index) => <div className={styles.specimen} key={seed.id}><FlowerVisual visualKey={seed.visualKey} bloomed /><strong>SPECIMEN 0{index + 1} / {seed.label}</strong><p>{seed.message}</p></div>)}</div><p className={styles.closing}>Tidak ada bunga di sini yang tumbuh secara kebetulan. Aku menanam setiap kata ini karena semuanya benar.</p><p className={styles.signature}>— Andre</p><dl><div><dt>SEEDS PLANTED</dt><dd>3</dd></div><div><dt>BLOOMS PRESERVED</dt><dd>3</dd></div><div><dt>STATUS</dt><dd>STILL GROWING</dd></div></dl><span className={styles.preservedStamp}>PRESERVED WITH CARE</span></article><div className={styles.folioActions}><button className={styles.primaryAction} type="button" onClick={onReplay}>Tumbuhkan lagi</button><Link to="/">Kembali ke koleksi</Link></div></div> }
